### ISSUE TITLE
Help to properly override CSS

### ISSUE THREAD

**Issue by guinuxbr** [reuixiy/hugo-theme-meme#108]
How can I properly overwrite the CSS without editing the theme files directly?

Maybe possible with this technique?
https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/3

But I found that Meme has a different structure where CSS definitions goes in:
**/layouts/partials/style.html** that is called by **/layouts/partials/head.html**, am I right?

I also found a **/layouts/partials/custom/head.html**

So, I am a little confuse in how to proceed. Can you help?

**Comment by reuixiy** [comment]
MemE uses SCSS via [Hugo Pipes](https://gohugo.io/hugo-pipes/introduction/) to generate CSS instead of static CSS file.

And MemE provides a [`_custom.scss`](https://github.com/reuixiy/hugo-theme-meme/blob/master/assets/scss/custom/_custom.scss) for customization. Just create a
`~/blog/assets/scss/custom/_custom.scss` file which will override
`~/blog/themes/meme/assets/scss/custom/_custom.scss`
and add your styles into this file.

Actually, you can override any template of theme in Hugo, see this mirror page I googled: https://gohugobrasil.netlify.com/themes/customizing/

**Comment by guinuxbr** [comment]
I had already read the documentation but, since Meme is too cool for me to mess up  :stuck_out_tongue_closed_eyes: , I was confused about how to implement the override in a proper way. 

Anyway, the built-in method with the help of **_custom.scss** works like a charm.
Maybe it is a good idea to place this explanation at the README.md file? Should I open a PR?

Thank you again.

P.S.: I have some feature request. Should I open a new Issue?

**Comment by reuixiy** [comment]
> Maybe it is a good idea to place this explanation at the README.md file? Should I open a PR?

Yep, welcome!

> I have some feature request. Should I open a new Issue?

Yes.

**Comment by guinuxbr** [comment]
PR opened.
