### ISSUE TITLE
SVG Header Issue [Linux / Firefox]

### ISSUE THREAD

**Issue by TokenBrice** [reuixiy/hugo-theme-meme#131]
Hi,

I've been scratching my head quite hard around this one - maybe I've missed something. Here's what I observe:

### SVG Header display issue 
- `Ubuntu 18.04, Firefox 76.0`

The header behaves erratically for readers using Firefox on Linux - confirmed by myself and a few friends. 

![svg-header](https://user-images.githubusercontent.com/28776588/81291199-a3113080-9069-11ea-9402-5eb72aa11cc7.gif)

More observations:
1. The homepage header usually displays alright, but going to any page (posts or regular page) leads to the display issue as shown in the gif.
2. When the header is not properly displayed on a page/post, a full refresh (CTRL+F5) fixes the issue for this page. (going to another page --> issue again)

I had to constrain the size of the logo a bit, directly in the /data/svg.toml, maybe that's related?

`brand = '<svg width="60%" height="60%" ...`

It displays properly on other browsers / OS.

**Comment by reuixiy** [comment]
> `brand = '<svg width="60%" height="60%" ...`

Yes, maybe related, maybe due to `%`.

I added [some documentation](https://github.com/reuixiy/hugo-theme-meme/blob/aa1461f7d110f97311195c37450ebd611b7cacb1/data/SVG.toml#L1-L15) in SVG.toml recently:

> ```
> # Also, please be sure to add `class` attribute into the SVG.
> # The value, `brand` for brand; `icon` for icons, i.e.
> #   `<svg ... class="brand">`
> #   `<svg ... class="icon">`
> ```

So you may need to add `class="brand"` into your svg tag, then you are able to resize your logo via [these params](https://github.com/reuixiy/hugo-theme-meme/blob/aa1461f7d110f97311195c37450ebd611b7cacb1/config-examples/en/config.toml#L274-L276), instead of `width="60%" height="60%"`.

**Comment by TokenBrice** [comment]
I did miss something! I was able to fix it on my local build thanks to your advice. Thanks for the help!
