### ISSUE TITLE
markdownify.html attempts to read config.toml

### ISSUE THREAD

**Issue by palant** [reuixiy/hugo-theme-meme#133]
Generation failed for me because `layouts/partials/utils/markdownify.html` attempted to read `config.toml` which doesn't exist in my case (I use the YAML config format). I'd say this file should use `.Site.Params.enableEmoji` rather than attempt to parse the config file?

**Comment by reuixiy** [comment]
Hmmm, I did this because I found that there is a [Hugo-defined variable](https://gohugo.io/getting-started/configuration/) `enableEmoji`, but it **cannot** access via [Site Variables](https://gohugo.io/variables/site/), and I don’t want to repeat it in `Params`.

Note that this theme [requires a configuration file](https://github.com/reuixiy/hugo-theme-meme#blogging) provided by the theme, which is already in TOML format. Did you just convert it to YAML format? If so, well...

Anyway, `readFile` seems quite rude indeed. I'll make a commit.

**Comment by palant** [comment]
Oh, I didn't realize that `enableEmoji` isn't under `params`, I see...

Yes, I had an existing YAML config, so I added the settings from your config example there.

**Comment by palant** [comment]
Unfortunately, `.RenderString` function is unaffected by this setting - emojis seem to be processed during parsing, not rendering.

**Comment by reuixiy** [comment]
Yes, neither `markdownify` nor `.RenderString` respect `enableEmoji`, and that's why I added this workaround in `layouts/partials/utils/markdownify.html`.

Also, I took a look at Issues of Hugo and found https://github.com/gohugoio/hugo/issues/7170.

**Comment by palant** [comment]
If moving the setting around is too much trouble, maybe you could use `readDir` to make sure the file actually exists so there is at least no error.

**Comment by reuixiy** [comment]
@palant Just submitted a commit and it should work.

**Comment by reuixiy** [comment]
wait a minute...

**Comment by reuixiy** [comment]
Okay, now it should work!

**Comment by palant** [comment]
Yes, seems to work, thank you!
