### ISSUE TITLE
Default theme is light even though it should be dark

### ISSUE THREAD

**Issue by hseagle2015** [reuixiy/hugo-theme-meme#201]
Hello,

I'm experiencing a weird problem where default theme is always light, even though I've configured dark in `config.toml`

```
enableDarkMode = true
defaultTheme = "dark"

hideThemeToggle = false
hideThemeToggleInHome = false
```

With this configuration, the site renders the light theme by default. If I toggle to dark theme, my browser gets the `theme=dark` key in the local storage and afterwards displays the site correctly with dark theme.

I'm using Hugo v0.72.0 and MemE theme v4.4.0.

**Comment by hseagle2015** [comment]
FWIW, until this bug is confirmed and resolved, I managed to fix the problem with a workaround solution.

I added few lines of JavaScript to `assets/js/custom.js` that basically check if the user selected specific theme style. If the user didn't choose prefered style, transition to dark theme kicks in.

```javascript
if (localStorage.getItem('theme') === null) {
  localStorage.setItem('theme', 'dark');
  changeModeMeta('dark');
}
```

**Comment by reuixiy** [comment]
Currently, [default theme](https://github.com/reuixiy/hugo-theme-meme/blob/f782a5998493e63bfed09d261da9ff4b2dcafa54/assets/scss/themes/_dark.scss#L47-L51) in `dark.scss` can be overridden by [`prefers-color-scheme`](https://github.com/reuixiy/hugo-theme-meme/blob/f782a5998493e63bfed09d261da9ff4b2dcafa54/assets/scss/themes/_light.scss#L35-L39) media query in `light.scss`, which caused this issue. And in my Linux laptop, which has no appearance option in system preferences, Chrome has this issue but Firefox works well.

Anyhow, I think this is a conflict between user prefers and site owner prefers. And I'm not sure if this is a bug, since MemE's principle is user prefers first.

But I think maybe we can do something for this, since dark theme is more special than "old" light theme. Perhaps we can restore the `data-theme` attribute in `<html>`?

```diff
- <html lang="{{ .Site.LanguageCode }}">
+ <html lang="{{ .Site.LanguageCode }}"{{ if and .Site.Params.enableDarkMode (eq .Site.Params.defaultTheme "dark") }} data-theme="dark"{{ end }}>
```

Or add a param in config.toml for site owner to control if MemE should override system preferences?

/cc @palant

**Comment by reuixiy** [comment]
Also, with [Chrome emulating prefers-color-scheme DevTools](https://web.dev/prefers-color-scheme/#emulating-prefers-color-scheme-in-devtools), I found MemE doesn't react on dark mode changes anymore, compared with [this demo](https://dark-mode-baseline.glitch.me/) by [web.dev](https://web.dev/prefers-color-scheme/#reacting-on-dark-mode-changes).

/cc @palant

**Comment by palant** [comment]
Yes, the `defaultTheme` setting is close to irrelevant now - it's the user's preference that matters, and almost all browsers can communicate this one now. I'd say that this is by design and the setting's description needs to be adapted if anything. Allowing web masters to override user's preferences makes little sense.

> Also, with [Chrome emulating prefers-color-scheme DevTools](https://web.dev/prefers-color-scheme/#emulating-prefers-color-scheme-in-devtools), I found MemE doesn't react on dark mode changes anymore, compared with [this demo](https://dark-mode-baseline.glitch.me/) by [web.dev](https://web.dev/prefers-color-scheme/#reacting-on-dark-mode-changes).

It does, for me. You have to clear `localStorage` on the site however - if the user chose a theme explicitly, it overrides `prefers-color-scheme` of course.

The only issue I see is the browsers not always determining correctly what the user wants, so `prefers-color-scheme` results are inconsistent. On my system (Kubuntu) Firefox correctly determines that my system is set to dark mode, but it won't care about its own theme. Chromium on the other hand uses light mode no matter how the system or the browser itself are configured.

**Comment by palant** [comment]
Actually, looking a bit further [the spec](https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-color-scheme) does not really specify how browsers are supposed to know whether the user wants a dark theme. However, [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) clearly says "if the user has requested the system use a light or dark color theme" - so only the system theme is relevant, not the browser theme.

Also, in Firefox one can set `ui.systemUsesDarkTheme` preference to 2. This means "no preference" and will override the system-wide setting. In this case MemE will fall back to the default theme set by the webmaster (yes, I tested this).

So I guess it's all expected behavior, merely Chrome is missing KDE integration.

**Comment by reuixiy** [comment]
Oh, that‘s why! It's a Chorme bug. 😬

But still, I think adding an option for MemE users to choose whether to override system's preferences is a harmless attempt :)
