### ISSUE TITLE
Optimise PageSpeed: Remove unused JavaScript

### ISSUE THREAD

**Issue by JinhangZhu** [reuixiy/hugo-theme-meme#250]
Hiya @reuixiy, thank you all time for your contribution. I was trying to check my site's [PageSpeed Insight](https://developers.google.com/speed/pagespeed/insights/) but encountered the following **long-runtimes issue**:

- Website link: https://www.jinhang.work/
- JavaScript URL: https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js
- Screenshot: ![image](https://user-images.githubusercontent.com/45664104/91516660-9f5a3000-e91e-11ea-9d2a-2136bb19ecbc.png)

 **Could you please tell me if I can remove it from the codes** since I hesitate to do so because it says `mathjax` which is crucial? I also had some other slow-loading issues but I guess there are easy solutions, so never mind.

**Comment by reuixiy** [comment]
1. Disable `enableMathJax` in config.toml, since it's global setting.
2. Create a `_index.md` under `content/tech/`, and add the following content,

   ```
   +++
   title = "Tech"
   [cascade]
     mathjax = true
   +++
   ```

   which means mathjax will be enabled in tech section (via [`cascade`](https://gohugo.io/content-management/front-matter#front-matter-cascade)) only.

**Comment by JinhangZhu** [comment]
@reuixiy Thanks for the solution. The issue was resolved!
