### ISSUE TITLE
[BUG] back to top arrow not showing on mobile

### ISSUE THREAD

**Issue by michael0liver** [reuixiy/hugo-theme-meme#280]
I have been testing out the theme on my iPhone. In portrait mode I can't get the back to top arrow to show up:
![image](https://user-images.githubusercontent.com/55017335/101979398-caaa2600-3c54-11eb-8b95-9c02b31fdb60.png)

In landscape it does appear:

![image](https://user-images.githubusercontent.com/55017335/101979406-d39af780-3c54-11eb-936a-e9db63f8b159.png)

Also I it might be better to set 
`apple-mobile-web-app-status-bar-style` to another option because text appears above the header like here:
![image](https://user-images.githubusercontent.com/55017335/101979476-4a37f500-3c55-11eb-94c6-b37cde2ad7e4.jpeg)
(This happens when you "Add to home")

**Comment by reuixiy** [comment]
1. > back to top arrow not showing on mobile

   It's a feature actually, since user can easily scroll to top on a mobile device. But we could/should add a option for it.
   https://github.com/reuixiy/hugo-theme-meme/blob/e927542dbe1cb8329acfe475bcd77df2361118f8/assets/scss/base/_responsive.scss#L10-L12

2. > Also I it might be better to set `apple-mobile-web-app-status-bar-style` to another option

   Agreed.

**Comment by reuixiy** [comment]
So just fixed that :)

1. Add a new param `displayBackToTopOnMobile` and set it to `true` in your config.toml, see https://github.com/reuixiy/hugo-theme-meme/commit/9d7ce997307cfca6cc79f9d557a7ebe889e39186
2. You may need to delete the app from your phone then re-add it to the home screen to see the changes

And you should update MemE to the latest version, firstly.

**Comment by michael0liver** [comment]
Thanks, good job !
